### PR TITLE
Optional tests

### PR DESCRIPTION
**Pull request by DavisVaughan**
Once QuantStack/xtensor-r#102 is all worked out, it might be nice to have some tests for roptional values over here. This adds one for roundtripping optional values, but I can add more as we solve more of the optional value issues.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Hey @DavisVaughan, if you rebase this on master, you will see the test pass against `xtensor-r` master for one of the items of the build matrix, and we will know if it did the job!

**Comment by DavisVaughan** [comment]
Oh so that's why you did that. Great idea

**Comment by SylvainCorlay** [comment]
Eventually we may want to make that test an allowed failure tonallow for backward incompatible changes

**Comment by SylvainCorlay** [comment]
It looks like it is failing even with the master xtensor-r branch.

I need to change the `cat` commands that occur in case of failure to skip files that don't exist.

**Comment by DavisVaughan** [comment]
I think that the `cat` statements were pointing at the wrong files (maybe from before the split to Xtensor.R). I fixed that, but it looks like the latex rd file is still pointing at the wrong location (is this one even necessary?).

From the info, I see that I think we need `xtensor-r/roptional.hpp` over here:
https://github.com/QuantStack/xtensor-r/blob/75bf55adbb1d9c96256e915ca7f90df2b1e88e6b/CMakeLists.txt#L49

**Comment by DavisVaughan** [comment]
We got a green light!

**Comment by SylvainCorlay** [comment]
Yes!

**Comment by SylvainCorlay** [comment]
We should be able to tag a release of xtensor-r!

**Comment by DavisVaughan** [comment]
Do we know what to do with this error? I can't really use the optional support effectively without it https://github.com/QuantStack/xtensor-r/pull/102#issuecomment-477654127

**Comment by SylvainCorlay** [comment]
> # error: cannot convert 'xtl::xoptional<int, bool>' to 'int' without a conversion operator

If you have a more complete error output handy, that would be nice.

**Comment by DavisVaughan** [comment]
I updated the comment with the full errror message

**Comment by SylvainCorlay** [comment]
Ok I made a PR to reproduce the issue in xtensor-r. It appears to be a bug with the inner types. Should be fixed by tomorrow hopefully.

**Comment by DavisVaughan** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
@DavisVaughan I have released `xtensor-r` 0.11 and updated `Xtensor.R` to reflect these changes.

This rebased PR should now build succesfully against master.

The issues with the reducers and optional values is an upstream xtensor issue that we will need to deal with in xtensor 0.21.0. It will be a bit more involved than initially expected.

**Comment by DavisVaughan** [comment]
Sounds great, thank you!

**Comment by SylvainCorlay** [comment]
> Sounds great, thank you!

Up to you if you want to upgrade to the latest for your demo :)

**Comment by DavisVaughan** [comment]
Oh, I run master of everything because I like the bleeding edge 🤣 https://github.com/DavisVaughan/Xtensor.R/blob/dev/tools/vendor#L1

**Comment by DavisVaughan** [comment]
FYI I think you will probably have to update that stupid git diff file too

**Comment by SylvainCorlay** [comment]
> FYI I think you will probably have to update that stupid git diff file too

Yes I was thinking about it.

**Comment by SylvainCorlay** [comment]
:tada:

**Pull request merged**
