### PR TITLE
Use `sh` directly rather than relying on shebang.

### PR DESCRIPTION
**Pull request by DavisVaughan**

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Also, you can always use `devtools::build_win()` (I think that's the name) to build on cran's windows machines without making an actual submission

**Comment by SylvainCorlay** [comment]
Thanks! It seems that the current master version does not yet passes CRAN tests:

**Comment by SylvainCorlay** [comment]
Weird since we continuously check the checks with appveyor.

**Comment by DavisVaughan** [comment]
Alright I have another idea, hold tight

**Pull request merged**
