### PR TITLE
Force `Biarch: true` because of the use of configure.win

### PR DESCRIPTION
**Pull request by DavisVaughan**

### CODE REVIEW

**Comment by DavisVaughan** [comment]
This seems to work https://win-builder.r-project.org/SH1hqNPtSpAH/

Learned about it from:
https://github.com/r-lib/remotes/issues/272

**Comment by SylvainCorlay** [comment]
Woot! This great! Thanks for helping with this.

**Comment by DavisVaughan** [comment]
I wonder if you need this option on appveyor:

https://support.rstudio.com/hc/en-us/articles/200486518-Customizing-Package-Build-Options

```
 --multiarch do runtime tests on all installed sub-archs
```

**Comment by DavisVaughan** [comment]
I don't think your current appveyor setup tests on i386, so setting `--multiarch` had no effect (in fact R told me, "only 1 architecture available"). 

https://ci.appveyor.com/project/DavisVaughan/xtensor-r#L667

https://github.com/QuantStack/Xtensor.R/blob/master/.appveyor.yml#L5

**Pull request merged**
